### ISSUE TITLE
I am struggling to simply open a local file

### ISSUE THREAD

**Issue by turner** [usnistgov/h5wasm#38]
The docs are very thin on doing this trivial task. I have passed a local file object to to h5wasm and it refuses to open the file even though permissions allow it to do so. 

Here file is a local file handed off to the File() method.

`const cndbf = new h5wasm.File(file.name, "r")`

My console fills with all manner of unintelligible errors. Apparently I don't have permissions to read the file.

What am I missing here?

Thanks,
Doug

**Comment by turner** [comment]
The code is throwing errors at this line in the `constructor` for `File`:

`file_id = Module.ccall("H5Fopen", "bigint", ["string", "number", "bigint"], [filename, h5_mode, 0n]);
`

**Comment by bmaranville** [comment]
Thanks for trying out h5wasm!  Are you trying to open local files using nodejs?  If so, see this section of the readme: https://github.com/usnistgov/h5wasm#nodejs

If you are trying to open files in the browser, this is more complicated and you have to "upload" them into the browser before opening (see https://github.com/usnistgov/h5wasm#web-helpers)

If those instructions are not working, please let me know!

**Comment by turner** [comment]
Brian,
I am looking at the file upload portion web-helpers code:

```
// Attach to a file input element:
// will save to Module.FS (memfs) with the name of the uploaded file
document.getElementById("upload_selector").onchange = uploader;
// file can be found with 
let f = new h5wasm.File(UPLOADED_FILES[UPLOADED_FILES.length -1], "r");

```
There is a bit of magic here with the input element that you need to clarify. I already have an onchange handler for loading a local file. Here it looks like you provide a replacement  with the "uploader". I am confused about how I am supposed to make this work with my pre-existing onchange handler.

**Comment by bmaranville** [comment]
Yes, there is some hidden stuff going on.  For reading with h5wasm, you have to write the buffer to the virtual filesystem provided by emscripten, that is used by the webassembly library.  

If you look here: https://github.com/usnistgov/h5wasm/blob/main/src/file_handlers.ts#L7 you can see how to get a handle to the FS object, then you have to use FS.writeFile as seen here: https://github.com/usnistgov/h5wasm/blob/main/src/file_handlers.ts#L13
Note that you have to await the ```ready``` object from h5wasm because the loading of the library is asynchronous, and the FS will not exist until the loading is complete.

Once the FS exists, FS.writeFile is synchronous, so you don't have to await it.  You have to provide a filename when writing a file, too - which is then used by h5wasm for opening (the hdf5 C library opens files by path on the available filesystem).

For example, if you have done
```js
FS.writeFile("myfile.hdf5", ab); // ab is an arraybuffer
// you can then do:
const f = new h5wasm.File("myfile.hdf5");
```

**Comment by turner** [comment]
I will look at the above. Just so we are clear, this is what I current have that does not work:

```
function configureLocalFileLoader(inputElement) {

    inputElement.addEventListener('change', async () => {

        const file = inputElement.files[ 0 ]
        
        const cndb = new h5wasm.File(file.name)

        cndb.close()
    })

}

```

**Comment by turner** [comment]
This issue was resolved as a jsfive issue. Thank again Brian
