### ISSUE TITLE
Adding `libhdf5_cpp.a` to the `libhdf5` branch?

### ISSUE THREAD

**Issue by LTLA** [usnistgov/h5wasm#8]
Would this be straightforward to do? I realized I could make my application more efficient by directly linking to your `libhdf5.a` during construction of my own Wasm binary; however, it's been a long time since I worked directly with the HDF5's C API, and I'm more familiar with the C++ flavor. If it's not a lot of extra effort, it might be generally useful to include `libhdf5_cpp.a` in the repo.

**Comment by bmaranville** [comment]
I've actually had trouble getting the cpp libraries to build in a sane way.  I got as far as determining something weird was going on as seen in https://github.com/emscripten-core/emscripten/issues/15131 - it looks like somewhere during the CMake build process, the variable `0` (yes, the actual numeral zero can be a variable in CMake?) has it's value set to "1", and then a later test fails when comparing the return code to `0` (when the return code is literally 0, and it should pass).

Perhaps someone with more CMake expertise than me can figure out what is going on!
In order to enable building of the cpp libraries, add this flag to the `$(WASM_LIBS)` section in the Makefile: `-DHDF5_BUILD_CPP_LIB=1` if you want to try it yourself.

**Comment by LTLA** [comment]
Hm, very surreal. I too struggle with CMake, but I'll give it a shot later this month. I'll re-open this issue and report back if I make any progress, otherwise I'll fall back to the C API.

**Comment by bmaranville** [comment]
I tried setting up the CMake build from a CMakeLists.txt so I could add some debugging options, and for some reason just running the build that way makes the problem go away.  It is as mysterious as why the problem was happening in the first place.

In any case, the libhdf5_cpp.a and libhdf5_hl_cpp.a were generated.  I am attaching them to the latest release inside libhdf5_wasm.tgz, instead of putting them in a separate branch, as this will be easier to maintain going forward (I will probably delete the libhdf5 branch)

**Comment by LTLA** [comment]
Great! I don't suppose you could throw in the C++ headers in `wasm_build/hdf5/include/` as well, if you didn't already? This would be helpful to make sure I'm using the appropriate versions of the headers when linking to your static library.

**Comment by bmaranville** [comment]
Huh... I don't know why they're not there already.  I just set the install path and the other headers were copied there automatically during `make install`.  I'll look into it.

**Comment by LTLA** [comment]
Sorry, I didn't check before posting - I can see them in the tarball, thanks.
